name: "Run Pest Tests"

on: [push]

jobs:
  phpunit:
    name: Run Pest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Create database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS testing;'

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/pest
        env:
          DB_PASSWORD: root
